-- 001_init.sql - accounts, throw-level match records, derived-stat cache.
--
-- Two ideas run through this schema, and everything else follows from them.
--
-- 1. STORE EVERY DART. The `throws` table is the source of truth; nothing else
--    here holds a statistic that cannot be recomputed from it. That is what
--    makes a new metric - one nobody has thought of yet - a code change rather
--    than a migration plus a request that everyone replay their matches.
--
-- 2. SHARED ENTITIES ARE GAME-AGNOSTIC. users, matches, legs, turns and throws
--    describe darts landing in a game, not any particular game's rules. What
--    Cricket needs and 501 doesn't (marks, points, which target was hit) lives
--    in turns.game_json, written by that game's stats module. Adding Around the
--    Clock or Killer therefore touches no table in this file.
--
-- Conventions: timestamps are ISO-8601 TEXT (sortable as strings, unambiguous
-- in a file someone may open in ten years); booleans are INTEGER 0/1, because
-- SQLite has no boolean and node:sqlite refuses to bind one.

-- ---------------------------------------------------------------------------
-- Accounts
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id                 INTEGER PRIMARY KEY,
  -- Stored already lower-cased and trimmed by the API, so the UNIQUE
  -- constraint is genuinely "one account per address" rather than one per
  -- capitalisation of it.
  email              TEXT    NOT NULL UNIQUE,
  display_name       TEXT    NOT NULL,
  password_hash      TEXT    NOT NULL,
  password_salt      TEXT    NOT NULL,
  created_at         TEXT    NOT NULL,
  -- Avatars are small and optional. Keeping them in the database rather than
  -- as files on disk means the single-file backup story stays true; the API
  -- caps the size so this cannot become the reason the file is huge.
  avatar_blob        BLOB,
  avatar_mime        TEXT,
  -- Preferences, used to pre-select the setup screen. Free text rather than a
  -- constrained set: the list of formats lives in medley.js and a CHECK here
  -- would be a second copy of it, guaranteed to fall behind.
  pref_format        TEXT,
  pref_out_rule      TEXT,
  -- Leaderboards rank self-reported scores from a peer-to-peer app, so
  -- appearing on one is opt-in rather than automatic.
  leaderboard_opt_in INTEGER NOT NULL DEFAULT 0
);

-- Opaque random tokens rather than JWTs: revoking one is a DELETE, and there
-- is no signing key to rotate or leak. They live in the database so a server
-- restart doesn't log everyone out.
CREATE TABLE sessions (
  token      TEXT    PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT    NOT NULL,
  expires_at TEXT    NOT NULL,
  user_agent TEXT
);

CREATE INDEX sessions_user_idx    ON sessions(user_id);
CREATE INDEX sessions_expiry_idx  ON sessions(expires_at);

-- ---------------------------------------------------------------------------
-- Matches
-- ---------------------------------------------------------------------------
CREATE TABLE matches (
  id          INTEGER PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Generated by the browser when the match ends. The upload queue retries
  -- after being offline, so the same match can arrive twice; this is what makes
  -- the second arrival a no-op instead of a duplicate.
  --
  -- Scoped to the user, not global: an online match is recorded independently
  -- by both players (peer-to-peer, no authoritative server, so there is no
  -- shared record), and each of those rows is legitimately its own.
  client_uuid TEXT    NOT NULL,
  mode        TEXT    NOT NULL,           -- 'local' | 'online'
  started_at  TEXT    NOT NULL,
  ended_at    TEXT    NOT NULL,
  duration_ms INTEGER NOT NULL,
  -- The full leg list as configured (see medley.js normalizeLeg), kept whole so
  -- a match can be described exactly as it was set up even if the format
  -- presets change later.
  format_json TEXT    NOT NULL,
  -- NULL when the match was drawn, which Count Up legs make genuinely possible.
  winner_seat INTEGER,
  drawn       INTEGER NOT NULL DEFAULT 0,
  UNIQUE (user_id, client_uuid)
);

-- The dashboard's "recent matches" and every time-windowed statistic read this
-- order, so it gets its own index rather than sorting the whole history.
CREATE INDEX matches_user_time_idx ON matches(user_id, ended_at DESC);

-- One row per seat in the match. "Seat" is the index the rules layer uses
-- (medley.js legsWon is indexed by it, and online play pins host to 0), so it
-- is the join key everywhere rather than a name.
CREATE TABLE match_players (
  match_id     INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  seat         INTEGER NOT NULL,
  display_name TEXT    NOT NULL,
  -- Which seat the owner of this row actually played. Everything on the stats
  -- page is "my" performance, so almost every query filters on it.
  is_self      INTEGER NOT NULL DEFAULT 0,
  legs_won     INTEGER NOT NULL DEFAULT 0,
  -- Sets do not exist in this app: medley.js models a match as an ordered list
  -- of legs and nothing else. The column is here so that adding sets later is a
  -- gameplay feature rather than a schema migration - it stays 0 until then,
  -- and no statistic reads it.
  sets_won     INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (match_id, seat)
);

-- A leg is one game within a match. `game` is the dispatch key for the stats
-- modules, which is why a leg of an unknown game is stored perfectly happily -
-- the engine skips what it has no module for instead of failing.
CREATE TABLE legs (
  id          INTEGER PRIMARY KEY,
  match_id    INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  leg_index   INTEGER NOT NULL,
  game        TEXT    NOT NULL,           -- 'x01' | 'cricket' | 'countup' | ...
  x01_start   INTEGER,                    -- x01 only: 301 / 501 / 701
  rules       TEXT,                       -- x01 only: double | siso | dido | master
  bull        TEXT,                       -- 'split' | 'full'
  rounds      INTEGER,                    -- countup only
  winner_seat INTEGER,                    -- NULL if the leg was drawn
  UNIQUE (match_id, leg_index)
);

CREATE INDEX legs_game_idx ON legs(game);

-- A turn is one visit to the board: up to three darts, or a single whole-turn
-- total typed in by someone who watched them land.
CREATE TABLE turns (
  id               INTEGER PRIMARY KEY,
  leg_id           INTEGER NOT NULL REFERENCES legs(id) ON DELETE CASCADE,
  turn_index       INTEGER NOT NULL,
  seat             INTEGER NOT NULL,
  darts            INTEGER NOT NULL,
  -- What the visit actually counted for, after busts and double-in are applied.
  scored           INTEGER NOT NULL DEFAULT 0,
  remaining_before INTEGER,               -- x01 only
  remaining_after  INTEGER,               -- x01 only
  bust             INTEGER NOT NULL DEFAULT 0,
  is_checkout      INTEGER NOT NULL DEFAULT 0,
  -- 'dart' (thrown or clicked one at a time) or 'quick' (whole-turn total).
  -- A quick-total turn has one throw row standing for the whole visit, so
  -- per-dart statistics have to exclude it - this is the flag that lets them.
  entry            TEXT    NOT NULL DEFAULT 'dart',
  -- The per-game visit payload: for Cricket, the three dart targets, the marks
  -- earned, points scored and running MPR. Every field in it is recomputable
  -- from the throws below plus the pure rules in cricket.js, so it is a
  -- convenience and never the only copy - a bug in it is fixable by
  -- rederivation rather than by asking for the matches back.
  game_json        TEXT,
  UNIQUE (leg_id, turn_index)
);

CREATE INDEX turns_leg_idx ON turns(leg_id);

-- One row per dart. This is the table everything else is derived from.
CREATE TABLE throws (
  id               INTEGER PRIMARY KEY,
  turn_id          INTEGER NOT NULL REFERENCES turns(id) ON DELETE CASCADE,
  dart_index       INTEGER NOT NULL,      -- 0..2 within the turn
  -- The raw SegmentID from granboard.js where there is one. Recording it means
  -- a scoring heatmap is a GROUP BY rather than a re-parse of a label.
  segment_id       INTEGER,
  section          TEXT    NOT NULL,      -- '20', 'BULL', 'Other', ...
  ring             TEXT    NOT NULL,      -- inner/triple/outer/double/bull/quick
  -- 1/2/3, which is SegmentType's value - see granboard.js, where the type
  -- doubles as the multiplier.
  multiplier       INTEGER NOT NULL DEFAULT 1,
  value            INTEGER NOT NULL,
  remaining_before INTEGER,
  remaining_after  INTEGER,
  bust             INTEGER NOT NULL DEFAULT 0,
  -- Thrown before satisfying a double-in requirement: a real dart that scored
  -- nothing. Counted as a dart thrown, excluded from scoring averages.
  ignored          INTEGER NOT NULL DEFAULT 0,
  -- Milliseconds since the match started, not a wall clock: it survives a
  -- timezone change and is what a "time between darts" metric would want.
  at_ms            INTEGER NOT NULL DEFAULT 0,
  UNIQUE (turn_id, dart_index)
);

CREATE INDEX throws_turn_idx ON throws(turn_id);

-- ---------------------------------------------------------------------------
-- Derived data
-- ---------------------------------------------------------------------------
-- Unlocked achievements only - a locked one is the absence of a row, so adding
-- a new achievement doesn't require backfilling anything.
CREATE TABLE achievements (
  user_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code      TEXT    NOT NULL,
  -- Which stats module declared it ('x01', 'cricket', or 'career'), so the
  -- dashboard can group them the same way the stats page groups metrics.
  game      TEXT    NOT NULL,
  earned_at TEXT    NOT NULL,
  match_id  INTEGER REFERENCES matches(id) ON DELETE SET NULL,
  PRIMARY KEY (user_id, code)
);

-- The one place a derived number is stored. It holds the stats engine's output
-- verbatim, is invalidated whenever a match is inserted, and can be deleted
-- wholesale at any time without losing anything - the next request rebuilds it
-- from the throws.
CREATE TABLE stats_cache (
  user_id         INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  matches_counted INTEGER NOT NULL,
  json            TEXT    NOT NULL,
  updated_at      TEXT    NOT NULL
);
